export type StageId =
  | "foundation"
  | "engineering"
  | "software"
  | "embedded"
  | "iot"
  | "practice";

export type CourseCategory =
  | "通用素养"
  | "数学建模"
  | "编程基础"
  | "电路硬件"
  | "嵌入式底层"
  | "通信感知"
  | "数据与应用"
  | "项目实践";

export type Course = {
  id: string;
  name: string;
  semester: number | "1-8" | "7-8";
  credits: number;
  category: CourseCategory;
  stage: StageId;
  importance: 1 | 2 | 3 | 4 | 5;
  focus: string;
  why: string;
  skills: string[];
  prerequisites: string[];
};

export type LearningStage = {
  id: StageId;
  title: string;
  subtitle: string;
  outcome: string;
};

export type CareerRole = {
  id: string;
  title: string;
  fit: string;
  demand: string[];
  courseIds: string[];
};

export type CurriculumMajor = {
  id: string;
  title: string;
  shortTitle: string;
  status: "已接入" | "待接入";
};

export type CurriculumDataset = {
  stats: { label: string; value: string; note: string }[];
  courses: Course[];
  careerRoles: CareerRole[];
  sourceNote: string;
};

export const curriculumMajors: CurriculumMajor[] = [
  {
    id: "electronic-iot",
    title: "电子信息工程（物联网方向）",
    shortTitle: "电子信息 · 物联网",
    status: "已接入",
  },
  {
    id: "electronic-info",
    title: "电子信息",
    shortTitle: "电子信息",
    status: "已接入",
  },
  {
    id: "mobile-internet",
    title: "电子信息工程（移动互联网方向）",
    shortTitle: "移动互联网",
    status: "已接入",
  },
  {
    id: "communication-engineering",
    title: "电子信息工程（通信工程方向）",
    shortTitle: "通信工程",
    status: "已接入",
  },
];

export const curriculumStats = [
  { label: "毕业总学分", value: "172", note: "专业培养方案要求" },
  { label: "实践教学", value: "800", note: "实践学时，偏应用型" },
  { label: "培养模式", value: "3+1", note: "三年校内 + 一年实训实习" },
  { label: "专业方向", value: "IoT", note: "电子信息工程物联网方向" },
];

export const learningStages: LearningStage[] = [
  {
    id: "foundation",
    title: "基础认知",
    subtitle: "数学、物理、编程入口",
    outcome: "能读懂工程问题，开始用程序描述问题。",
  },
  {
    id: "engineering",
    title: "电路与电子",
    subtitle: "从电路到信号",
    outcome: "能分析硬件单元，理解电子系统如何采集和传输信号。",
  },
  {
    id: "software",
    title: "软件与数据",
    subtitle: "算法、Java、数据库",
    outcome: "能组织数据、写业务逻辑，为物联网应用层打底。",
  },
  {
    id: "embedded",
    title: "嵌入式底层",
    subtitle: "单片机、ARM、RTOS、Linux",
    outcome: "能把传感器、控制器和操作系统连接起来。",
  },
  {
    id: "iot",
    title: "物联网系统",
    subtitle: "传感、无线、客户端、安全",
    outcome: "能把设备、网络、数据和应用组合成完整方案。",
  },
  {
    id: "practice",
    title: "项目与就业",
    subtitle: "综合实训、岗位实习、毕业设计",
    outcome: "把课程能力沉淀为项目经验、作品集和岗位技能。",
  },
];

export const courses: Course[] = [
  {
    id: "calculus-1",
    name: "高等数学 AI",
    semester: 1,
    credits: 5,
    category: "数学建模",
    stage: "foundation",
    importance: 5,
    focus: "函数、极限、微积分基础",
    why: "为电路、信号、通信、控制等课程提供连续系统分析能力。",
    skills: ["数学建模", "公式推导", "工程抽象"],
    prerequisites: [],
  },
  {
    id: "c-language",
    name: "C 语言程序设计",
    semester: 1,
    credits: 3,
    category: "编程基础",
    stage: "foundation",
    importance: 5,
    focus: "语法、指针、结构体、过程化编程",
    why: "嵌入式开发的入口课程，后续 ARM、单片机、RTOS 都会用到。",
    skills: ["C 语言", "调试思维", "内存理解"],
    prerequisites: [],
  },
  {
    id: "c-practice",
    name: "C 语言编程实践",
    semester: 1,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "小程序、数组、文件与综合练习",
    why: "把语法变成可运行的程序，是后续工程实践的最低门槛。",
    skills: ["编码规范", "问题拆解", "程序调试"],
    prerequisites: ["c-language"],
  },
  {
    id: "computer-basic",
    name: "大学计算机基础",
    semester: 1,
    credits: 1,
    category: "通用素养",
    stage: "foundation",
    importance: 3,
    focus: "计算机系统、办公与信息素养",
    why: "帮助学生建立工具意识和数字化表达能力。",
    skills: ["信息检索", "文档处理", "基础计算思维"],
    prerequisites: [],
  },
  {
    id: "english-1",
    name: "大学英语 AⅠ",
    semester: 1,
    credits: 4,
    category: "通用素养",
    stage: "foundation",
    importance: 5,
    focus: "英语阅读、词汇积累、基础表达",
    why: "专业英文资料、开发文档、设备手册和考研英语都需要从第一学期持续积累。",
    skills: ["英语阅读", "词汇积累", "基础表达"],
    prerequisites: [],
  },
  {
    id: "english-2",
    name: "大学英语 AⅡ",
    semester: 2,
    credits: 4,
    category: "通用素养",
    stage: "foundation",
    importance: 5,
    focus: "英语阅读、写作、翻译和技术资料理解",
    why: "承接大学英语 AⅠ，让学生逐步能读懂英文技术说明、芯片资料和项目文档。",
    skills: ["英语阅读", "翻译表达", "技术资料理解"],
    prerequisites: ["english-1"],
  },
  {
    id: "english-3",
    name: "大学英语 AⅢ",
    semester: 3,
    credits: 2,
    category: "通用素养",
    stage: "foundation",
    importance: 5,
    focus: "专业资料阅读、考研英语、工程表达",
    why: "第三学期继续保持英语训练，避免专业课变多后英语能力断档。",
    skills: ["专业阅读", "考研英语", "工程表达"],
    prerequisites: ["english-2"],
  },
  {
    id: "calculus-2",
    name: "高等数学 AII",
    semester: 2,
    credits: 5,
    category: "数学建模",
    stage: "foundation",
    importance: 5,
    focus: "微分方程、级数、多元函数",
    why: "支撑信号与系统、通信原理、数字信号处理等连续与离散模型。",
    skills: ["系统建模", "数学分析", "工程计算"],
    prerequisites: ["calculus-1"],
  },
  {
    id: "linear-algebra",
    name: "线性代数",
    semester: 2,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "矩阵、向量空间、线性变换",
    why: "为信号处理、控制仿真、数据分析提供数学工具。",
    skills: ["矩阵计算", "数据表达", "算法基础"],
    prerequisites: ["calculus-1"],
  },
  {
    id: "circuit",
    name: "电路分析",
    semester: 2,
    credits: 5,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "电路定律、暂态稳态、频域分析",
    why: "所有硬件、传感、通信课程的底层基础。",
    skills: ["电路计算", "仪器测量", "故障分析"],
    prerequisites: ["calculus-1"],
  },
  {
    id: "mcu",
    name: "单片机与接口技术",
    semester: 2,
    credits: 2.5,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 5,
    focus: "I/O、中断、定时器、外设接口",
    why: "把程序写进硬件，是理解物联网终端设备的关键课程。",
    skills: ["单片机开发", "接口调试", "外设控制"],
    prerequisites: ["c-language", "circuit"],
  },
  {
    id: "python-basic",
    name: "大学计算机基础 II",
    semester: 2,
    credits: 1,
    category: "编程基础",
    stage: "software",
    importance: 3,
    focus: "Python 语言程序设计",
    why: "补充脚本化处理和数据分析能力，适合作为实验工具。",
    skills: ["Python", "数据处理", "自动化脚本"],
    prerequisites: ["computer-basic"],
  },
  {
    id: "probability",
    name: "概率论与数理统计",
    semester: 3,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "随机变量、统计推断、误差分析",
    why: "为通信、信号处理、实验数据分析提供概率与统计基础。",
    skills: ["统计分析", "误差判断", "数据解释"],
    prerequisites: ["calculus-2", "linear-algebra"],
  },
  {
    id: "analog-electronics",
    name: "模拟电子技术",
    semester: 3,
    credits: 5,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "二极管、三极管、放大电路、运放",
    why: "连接传感器信号和真实电路，是硬件岗位的核心基础。",
    skills: ["模拟电路", "参数测量", "电路调试"],
    prerequisites: ["circuit"],
  },
  {
    id: "embedded-linux",
    name: "嵌入式操作系统",
    semester: 3,
    credits: 2.5,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 5,
    focus: "Linux 操作系统、进程、文件、驱动基础",
    why: "支撑物联网网关、边缘设备和嵌入式应用开发。",
    skills: ["Linux", "进程管理", "系统调用"],
    prerequisites: ["c-language", "computer-basic"],
  },
  {
    id: "arm",
    name: "ARM 体系结构与接口技术",
    semester: 3,
    credits: 4,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 5,
    focus: "Cortex-M、外设接口、底层控制",
    why: "面向企业真实嵌入式平台，是从单片机过渡到工程开发的主干课。",
    skills: ["ARM", "Cortex-M", "底层接口"],
    prerequisites: ["c-language", "mcu", "digital-electronics"],
  },
  {
    id: "arm-practice",
    name: "ARM 编程实践",
    semester: 3,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "接口程序、外设控制、工程调试",
    why: "把 ARM 理论变成可验证的硬件作品。",
    skills: ["硬件调试", "寄存器配置", "项目记录"],
    prerequisites: ["arm", "c-language"],
  },
  {
    id: "digital-electronics",
    name: "数字电子技术",
    semester: 4,
    credits: 5,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "逻辑门、触发器、组合/时序电路",
    why: "为数字系统、嵌入式接口和硬件逻辑设计打基础。",
    skills: ["数字逻辑", "时序分析", "硬件验证"],
    prerequisites: ["circuit", "analog-electronics"],
  },
  {
    id: "signals",
    name: "信号与系统",
    semester: 4,
    credits: 3,
    category: "通信感知",
    stage: "engineering",
    importance: 5,
    focus: "连续/离散信号、系统响应、频域分析",
    why: "是通信原理、数字信号处理和控制仿真的桥梁课程。",
    skills: ["信号分析", "频域思维", "系统建模"],
    prerequisites: ["calculus-2", "linear-algebra", "circuit"],
  },
  {
    id: "data-structure",
    name: "数据结构",
    semester: 4,
    credits: 2.5,
    category: "编程基础",
    stage: "software",
    importance: 4,
    focus: "线性表、树、图、查找与排序",
    why: "提升程序设计质量，是客户端开发和数据处理的基础。",
    skills: ["算法思维", "复杂度分析", "数据组织"],
    prerequisites: ["c-language"],
  },
  {
    id: "java",
    name: "面向对象程序设计",
    semester: 4,
    credits: 3,
    category: "编程基础",
    stage: "software",
    importance: 4,
    focus: "Java、面向对象、异常、集合",
    why: "承接 Android 客户端和企业应用开发能力。",
    skills: ["Java", "OOP", "工程封装"],
    prerequisites: ["c-language", "data-structure"],
  },
  {
    id: "pcb",
    name: "印刷电路板设计",
    semester: 4,
    credits: 1,
    category: "电路硬件",
    stage: "engineering",
    importance: 4,
    focus: "原理图、PCB 布局布线、制板规范",
    why: "让硬件方案从电路图走向可生产的板级实现。",
    skills: ["PCB 设计", "器件选型", "硬件规范"],
    prerequisites: ["circuit", "analog-electronics", "digital-electronics"],
  },
  {
    id: "java-practice",
    name: "Java + MySQL 实训",
    semester: 4,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "面向对象项目、数据库连接、简单业务系统",
    why: "把 Java 和数据库组合起来，形成应用开发小闭环。",
    skills: ["Java 项目", "JDBC", "CRUD"],
    prerequisites: ["java", "database"],
  },
  {
    id: "dsp",
    name: "数字信号处理技术",
    semester: 5,
    credits: 2.5,
    category: "通信感知",
    stage: "engineering",
    importance: 4,
    focus: "采样、滤波、FFT、数字系统",
    why: "支撑传感数据处理、通信系统和智能感知应用。",
    skills: ["DSP", "滤波", "频谱分析"],
    prerequisites: ["signals", "probability"],
  },
  {
    id: "database",
    name: "数据库原理",
    semester: 5,
    credits: 3,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "SQL、MySQL、表结构、事务",
    why: "物联网数据采集之后需要存储、查询和分析，数据库是应用层核心。",
    skills: ["SQL", "MySQL", "数据建模"],
    prerequisites: ["data-structure"],
  },
  {
    id: "rtos",
    name: "实时操作系统与实验",
    semester: 5,
    credits: 2.5,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 5,
    focus: "任务调度、实时性、同步通信",
    why: "面向多任务设备控制，是嵌入式岗位的重要分水岭。",
    skills: ["RTOS", "任务调度", "实时控制"],
    prerequisites: ["embedded-linux", "arm"],
  },
  {
    id: "rf",
    name: "高频电子线路",
    semester: 5,
    credits: 2.5,
    category: "通信感知",
    stage: "engineering",
    importance: 4,
    focus: "高频放大、振荡、调制解调",
    why: "理解无线通信硬件链路，为短距离无线通信和通信原理做铺垫。",
    skills: ["射频基础", "调制解调", "电路测量"],
    prerequisites: ["analog-electronics", "signals"],
  },
  {
    id: "sensor",
    name: "传感器原理及应用",
    semester: 5,
    credits: 2,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "传感器机理、信号采集、应用设计",
    why: "物联网的感知层核心课程，直接决定设备能否采集真实世界数据。",
    skills: ["传感器选型", "数据采集", "信号调理"],
    prerequisites: ["analog-electronics", "mcu"],
  },
  {
    id: "rtos-practice",
    name: "RTOS 应用开发实训",
    semester: 5,
    credits: 2,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "任务拆分、设备控制、实时系统调试",
    why: "强化嵌入式项目能力，适合沉淀作品集。",
    skills: ["多任务编程", "嵌入式项目", "调试记录"],
    prerequisites: ["rtos", "arm-practice"],
  },
  {
    id: "sensor-practice",
    name: "传感器应用设计项目实训",
    semester: 5,
    credits: 2,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "传感采集、接口连接、数据展示",
    why: "把感知层、嵌入式和应用层串起来，是物联网项目雏形。",
    skills: ["传感项目", "系统联调", "实验报告"],
    prerequisites: ["sensor", "mcu", "database"],
  },
  {
    id: "mysql-practice",
    name: "MySQL 数据库实践",
    semester: 5,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "SQL 查询、表设计、数据维护",
    why: "让数据库从概念变成项目中可操作的能力。",
    skills: ["SQL 实操", "数据维护", "应用联调"],
    prerequisites: ["database"],
  },
  {
    id: "communication",
    name: "通信原理",
    semester: 6,
    credits: 2.5,
    category: "通信感知",
    stage: "engineering",
    importance: 4,
    focus: "调制、编码、信道、通信系统",
    why: "解释物联网设备如何可靠传输数据，是无线通信技术的理论支撑。",
    skills: ["通信系统", "信道理解", "链路分析"],
    prerequisites: ["signals", "probability", "rf"],
  },
  {
    id: "electromagnetic",
    name: "工程电磁场",
    semester: 6,
    credits: 2,
    category: "电路硬件",
    stage: "engineering",
    importance: 3,
    focus: "电磁场、电磁波、工程应用",
    why: "帮助理解无线传输、天线、干扰和电磁兼容问题。",
    skills: ["电磁分析", "工程解释", "EMC 意识"],
    prerequisites: ["calculus-2"],
  },
  {
    id: "android",
    name: "物联网客户端开发",
    semester: 6,
    credits: 2,
    category: "数据与应用",
    stage: "iot",
    importance: 5,
    focus: "Android 客户端、数据展示、设备交互",
    why: "面向用户侧应用，把设备数据变成可操作的产品界面。",
    skills: ["Android", "接口调用", "移动端交互"],
    prerequisites: ["java", "database"],
  },
  {
    id: "wireless",
    name: "短距离无线通信技术",
    semester: 6,
    credits: 1.5,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "短距离协议、组网、无线模块调试",
    why: "连接感知设备和网关，是物联网系统能否联网的核心环节。",
    skills: ["无线组网", "协议理解", "模块调试"],
    prerequisites: ["communication", "rf", "mcu"],
  },
  {
    id: "android-practice",
    name: "客户端开发实训",
    semester: 6,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "Android 页面、接口联调、数据可视化",
    why: "把应用开发能力落实到可演示的软件作品。",
    skills: ["移动端项目", "接口联调", "UI 数据呈现"],
    prerequisites: ["android", "mysql-practice"],
  },
  {
    id: "wireless-lab",
    name: "短距离无线通信实验",
    semester: 6,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "无线模块实验、数据传输、链路测试",
    why: "验证无线通信链路，补齐物联网系统联调能力。",
    skills: ["无线测试", "链路排错", "实验分析"],
    prerequisites: ["wireless"],
  },
  {
    id: "iot-project",
    name: "物联网应用项目综合实训",
    semester: 7,
    credits: 8,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "企业项目、系统集成、完整方案交付",
    why: "培养方案中标星的高支撑课程，是从学生作品走向岗位能力的关键节点。",
    skills: ["系统集成", "项目交付", "团队协作", "工程文档"],
    prerequisites: ["sensor-practice", "rtos-practice", "android-practice", "wireless-lab"],
  },
  {
    id: "iot-security",
    name: "物联网信息安全",
    semester: 7,
    credits: 2,
    category: "数据与应用",
    stage: "iot",
    importance: 3,
    focus: "设备、网络、数据安全基础",
    why: "面向实际系统的安全风险，适合做运维和系统集成方向补强。",
    skills: ["安全意识", "风险评估", "安全配置"],
    prerequisites: ["wireless", "database", "android"],
  },
  {
    id: "graduation-design",
    name: "毕业设计",
    semester: "7-8",
    credits: 12,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "选题论证、设计实现、实验分析、论文写作",
    why: "把四年课程和企业项目沉淀为可答辩、可展示的综合成果。",
    skills: ["课题设计", "工程实现", "论文写作", "答辩表达"],
    prerequisites: ["iot-project"],
  },
  {
    id: "internship",
    name: "岗位实习",
    semester: 8,
    credits: 3,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "企业岗位、真实任务、职业规范",
    why: "3+1 模式的就业衔接环节，用真实工作检验课程体系。",
    skills: ["岗位适应", "工程协作", "职业规范"],
    prerequisites: ["iot-project"],
  }
];

export const careerRoles: CareerRole[] = [
  {
    id: "embedded",
    title: "嵌入式/单片机开发工程师",
    fit: "对应真实岗位里的嵌入式软件、单片机固件、设备端开发，核心不是只会写 C，而是能把代码跑在板子上并完成现场调试。",
    demand: [
      "熟练 C/C++，能读懂数据手册、原理图和外设时序",
      "掌握 STM32/ESP32/Cortex-M，熟悉 UART、SPI、I2C、CAN、PWM、ADC",
      "了解 FreeRTOS/RT-Thread 或嵌入式 Linux，能做任务调度、驱动适配和资源管理",
      "会用 Keil/STM32CubeIDE/GCC、Git、J-Link/ST-Link、串口工具、示波器/逻辑分析仪调试",
      "理解 MQTT/Modbus/TCP/IP 等设备通信协议，能完成传感器、网关或云平台联调"
    ],
    courseIds: ["c-language", "mcu", "arm", "embedded-linux", "rtos", "arm-practice", "rtos-practice", "iot-project"],
  },
  {
    id: "hardware",
    title: "电子硬件/测试工程师",
    fit: "对应硬件助理工程师、硬件测试、电子测试岗位，市场更看重仪器使用、测试文档、问题定位和板级调试闭环。",
    demand: [
      "能读懂原理图和 PCB，理解模拟/数字电路、电源、接口和传感器信号链",
      "熟悉 Altium Designer/嘉立创 EDA 等原理图与 PCB 基础流程",
      "会使用万用表、示波器、信号发生器、电源、逻辑分析仪做测试和排障",
      "能编写测试计划、测试用例、测试报告，记录复现步骤和异常波形",
      "了解 EMC/ESD、可靠性、温升、电源纹波等量产前常见验证项"
    ],
    courseIds: ["circuit", "analog-electronics", "digital-electronics", "pcb", "sensor", "sensor-practice", "rf"],
  },
  {
    id: "iot-app",
    title: "物联网应用/Android 开发",
    fit: "对应 Android 客户端、设备 App、物联网可视化应用岗位，重点是手机端和设备/服务端稳定联动。",
    demand: [
      "掌握 Java 或 Kotlin，熟悉 Android Studio、Activity/Fragment、生命周期和权限",
      "熟悉 MVVM、Jetpack、RecyclerView、Room/SQLite 等常见 Android 工程结构",
      "能用 Retrofit/OkHttp 调 REST API，处理 JSON、登录鉴权、异常和弱网重试",
      "了解 BLE/蓝牙、Wi-Fi 配网、MQTT/WebSocket 等设备连接场景",
      "具备 Git 协作、日志定位、性能优化、基础 UI 适配和应用发布意识"
    ],
    courseIds: ["data-structure", "java", "database", "mysql-practice", "android", "android-practice", "iot-project"],
  },
  {
    id: "integration",
    title: "物联网系统集成/运维工程师",
    fit: "对应物联网实施、系统集成、运维交付岗位，真实工作经常是设备接入、网络排障、平台配置、现场交付。",
    demand: [
      "熟悉 TCP/IP、HTTP、MQTT、Modbus、串口通信和常见网关/传感器接入方式",
      "会 Linux 基础命令、日志排查、服务部署，了解 Docker、Nginx、Shell 更加分",
      "能操作 MySQL/PostgreSQL/Redis 等基础数据服务，理解设备数据表和告警数据流",
      "了解阿里云/华为云/OneNET 等 IoT 平台的设备接入、规则引擎、数据转发",
      "能写实施文档、拓扑图、验收报告，具备现场沟通和快速定位问题能力"
    ],
    courseIds: ["sensor", "wireless", "database", "android", "iot-security", "iot-project", "internship"],
  },
  {
    id: "communication",
    title: "通信与信号处理助理工程师",
    fit: "对应通信算法助理、信号处理、测试仿真类岗位，入门岗位通常要求会建模、仿真、分析数据，并能和硬件/算法团队配合验证。",
    demand: [
      "掌握信号与系统、通信原理、数字信号处理，能解释采样、滤波、调制、信道和频谱",
      "熟悉 MATLAB/Simulink 或 Python/Numpy/Scipy，能做算法仿真和数据可视化",
      "了解 C/C++ 实现、定点化、实时性约束，能把仿真算法向工程实现靠拢",
      "了解射频链路、频谱仪/矢量信号源/示波器等测试仪器更有竞争力",
      "加分项：了解 FPGA/DSP 平台、Verilog/VHDL、无线协议或雷达/声学/图像信号处理场景"
    ],
    courseIds: ["calculus-2", "linear-algebra", "signals", "dsp", "communication", "wireless-lab"],
  },
  {
    id: "postgraduate",
    title: "考研/升学备考",
    fit: "适合准备考电子信息、通信工程、控制、计算机交叉方向研究生的学生。",
    demand: ["高等数学、线代、概率长期复盘", "英语和政治提前滚动", "电路/信号/通信按目标院校二选一强化", "用毕业设计沉淀研究型表达"],
    courseIds: [
      "calculus-1",
      "calculus-2",
      "linear-algebra",
      "probability",
      "english-1",
      "english-2",
      "english-3",
      "circuit",
      "signals",
      "dsp",
      "communication",
      "data-structure",
      "graduation-design",
    ],
  },
];

export const electronicInfoStats = [
  { label: "毕业总学分", value: "170", note: "25 版培养方案要求" },
  { label: "实践教学", value: "846", note: "实践学时，强化工程能力" },
  { label: "培养模式", value: "3.5+0.5", note: "校内培养 + 企业实习" },
  { label: "专业方向", value: "EI", note: "电子设备、通信与智能系统" },
];

export const electronicInfoCourses: Course[] = [
  {
    id: "ei-calculus-1",
    name: "高等数学 AⅠ",
    semester: 1,
    credits: 5,
    category: "数学建模",
    stage: "foundation",
    importance: 5,
    focus: "极限、微积分、工程函数建模",
    why: "电子信息后续的电路、信号、通信和控制都依赖连续系统数学基础。",
    skills: ["数学建模", "工程计算", "公式推导"],
    prerequisites: [],
  },
  {
    id: "ei-english-1",
    name: "大学英语 AⅠ",
    semester: 1,
    credits: 3,
    category: "通用素养",
    stage: "foundation",
    importance: 5,
    focus: "英语阅读、词汇积累、基础表达",
    why: "电子信息学生后续会接触英文芯片手册、设备资料、论文摘要和考研英语，需要从第一学期持续积累。",
    skills: ["英语阅读", "词汇积累", "基础表达"],
    prerequisites: [],
  },
  {
    id: "ei-c-language",
    name: "C 语言程序设计",
    semester: 1,
    credits: 2.5,
    category: "编程基础",
    stage: "foundation",
    importance: 5,
    focus: "C 语言语法、数组、指针、结构体和工程化程序设计",
    why: "电子信息岗位常见的单片机、驱动、测试脚本和算法实现都需要 C 基础。",
    skills: ["C 语言", "调试思维", "嵌入式入口"],
    prerequisites: [],
  },
  {
    id: "ei-ai-basic",
    name: "计算机与人工智能基础",
    semester: 1,
    credits: 1,
    category: "编程基础",
    stage: "foundation",
    importance: 4,
    focus: "计算机基础、AI 基本概念和数字化工具使用",
    why: "25 版方案嵌入人工智能技术，这门课是后续 AI 融合课程的入口。",
    skills: ["计算思维", "AI 认知", "工具使用"],
    prerequisites: [],
  },
  {
    id: "ei-english-2",
    name: "大学英语 AⅡ",
    semester: 2,
    credits: 3,
    category: "通用素养",
    stage: "foundation",
    importance: 5,
    focus: "英语阅读、写作、翻译和技术资料理解",
    why: "承接大学英语 AⅠ，帮助学生逐步读懂英文器件文档、通信资料和开发说明。",
    skills: ["英语阅读", "翻译表达", "技术资料理解"],
    prerequisites: ["ei-english-1"],
  },
  {
    id: "ei-calculus-2",
    name: "高等数学 AⅡ",
    semester: 2,
    credits: 5,
    category: "数学建模",
    stage: "foundation",
    importance: 5,
    focus: "多元函数、微分方程、级数",
    why: "支撑信号与系统、通信原理、DSP 和电磁场的数学表达。",
    skills: ["系统建模", "微分方程", "工程分析"],
    prerequisites: ["ei-calculus-1"],
  },
  {
    id: "ei-linear-algebra",
    name: "线性代数",
    semester: 2,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "矩阵、向量空间、线性变换",
    why: "支撑 MATLAB 仿真、信号处理、AI 模型和数据分析。",
    skills: ["矩阵计算", "算法基础", "数据表达"],
    prerequisites: ["ei-calculus-1"],
  },
  {
    id: "ei-python",
    name: "Python 语言程序设计",
    semester: 2,
    credits: 1.5,
    category: "编程基础",
    stage: "software",
    importance: 4,
    focus: "Python 编程、数据处理和自动化脚本",
    why: "真实岗位中 Python 常用于测试自动化、数据分析、仿真和 AI 工具链。",
    skills: ["Python", "数据处理", "脚本自动化"],
    prerequisites: ["ei-ai-basic"],
  },
  {
    id: "ei-circuit",
    name: "电路分析",
    semester: 2,
    credits: 5,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "电路定律、暂态稳态、频域分析和实验测量",
    why: "电子设备研发、硬件测试、通信系统调试的基础能力。",
    skills: ["电路计算", "仪器测量", "故障定位"],
    prerequisites: ["ei-calculus-1"],
  },
  {
    id: "ei-c-practice",
    name: "C 语言工程实践",
    semester: 2,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "工程化 C 程序、小项目、调试和文档",
    why: "把语法能力转换为可展示的程序作品，为单片机和微机课程打基础。",
    skills: ["C 项目", "程序调试", "工程文档"],
    prerequisites: ["ei-c-language"],
  },
  {
    id: "ei-english-3",
    name: "大学英语 AⅢ",
    semester: 3,
    credits: 2,
    category: "通用素养",
    stage: "foundation",
    importance: 5,
    focus: "专业资料阅读、考研英语、工程表达",
    why: "第三学期继续保持英语训练，支撑后续专业英语、论文检索和升学准备。",
    skills: ["专业阅读", "考研英语", "工程表达"],
    prerequisites: ["ei-english-2"],
  },
  {
    id: "ei-data-structure",
    name: "数据结构",
    semester: 3,
    credits: 2,
    category: "编程基础",
    stage: "software",
    importance: 4,
    focus: "线性表、树、图、查找与排序",
    why: "支撑嵌入式软件、数据分析、算法仿真和考研计算机方向专业课。",
    skills: ["算法思维", "复杂度分析", "数据组织"],
    prerequisites: ["ei-c-language"],
  },
  {
    id: "ei-digital-electronics",
    name: "数字电子技术",
    semester: 3,
    credits: 5,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "逻辑门、触发器、组合/时序电路",
    why: "连接 MCU、FPGA、数字接口和硬件逻辑设计。",
    skills: ["数字逻辑", "时序分析", "接口理解"],
    prerequisites: ["ei-circuit"],
  },
  {
    id: "ei-analog-electronics",
    name: "模拟电子技术",
    semester: 3,
    credits: 5,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "二极管、三极管、运放、放大与滤波电路",
    why: "硬件研发和测试岗位高频要求能看懂模拟信号链和电源/放大电路。",
    skills: ["模拟电路", "信号调理", "电路调试"],
    prerequisites: ["ei-circuit"],
  },
  {
    id: "ei-probability",
    name: "概率论与数理统计",
    semester: 3,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "随机变量、统计推断、误差分析",
    why: "支撑通信、DSP、实验数据分析和 AI 模型评价。",
    skills: ["统计分析", "误差判断", "数据解释"],
    prerequisites: ["ei-calculus-2", "ei-linear-algebra"],
  },
  {
    id: "ei-matlab-practice",
    name: "MATLAB 仿真及应用实践",
    semester: 3,
    credits: 1,
    category: "通信感知",
    stage: "engineering",
    importance: 4,
    focus: "MATLAB 建模、信号仿真、数据可视化",
    why: "通信和信号处理类岗位常要求 MATLAB/Python 仿真能力。",
    skills: ["MATLAB", "仿真建模", "数据可视化"],
    prerequisites: ["ei-linear-algebra", "ei-python"],
  },
  {
    id: "ei-circuit-sim",
    name: "电路设计与仿真实验",
    semester: 3,
    credits: 1,
    category: "电路硬件",
    stage: "practice",
    importance: 4,
    focus: "电路仿真、参数验证、实验报告",
    why: "连接理论电路和真实硬件测试，是硬件岗位的重要训练。",
    skills: ["电路仿真", "实验验证", "报告撰写"],
    prerequisites: ["ei-circuit"],
  },
  {
    id: "ei-signals",
    name: "信号与系统",
    semester: 4,
    credits: 5,
    category: "通信感知",
    stage: "engineering",
    importance: 5,
    focus: "连续/离散信号、系统响应、频域分析",
    why: "是通信原理、DSP、控制和信号处理岗位的核心桥梁。",
    skills: ["信号分析", "频域思维", "系统建模"],
    prerequisites: ["ei-calculus-2", "ei-linear-algebra", "ei-circuit"],
  },
  {
    id: "ei-rf",
    name: "高频电子线路",
    semester: 4,
    credits: 3.5,
    category: "通信感知",
    stage: "engineering",
    importance: 4,
    focus: "高频放大、振荡、调制解调",
    why: "支撑通信链路、射频测试、无线设备和天线相关方向。",
    skills: ["射频基础", "调制解调", "高频测试"],
    prerequisites: ["ei-analog-electronics", "ei-signals"],
  },
  {
    id: "ei-matlab",
    name: "计算方法与 MATLAB 应用",
    semester: 4,
    credits: 3,
    category: "通信感知",
    stage: "engineering",
    importance: 4,
    focus: "数值计算、MATLAB 工程应用、算法验证",
    why: "为信号处理、通信仿真和工程数据分析提供工具能力。",
    skills: ["数值计算", "MATLAB", "算法验证"],
    prerequisites: ["ei-matlab-practice", "ei-probability"],
  },
  {
    id: "ei-tech-design",
    name: "电子技术课程设计",
    semester: 4,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "模拟/数字电路综合设计、制作和调试",
    why: "把模电数电能力转换成可演示的电子系统作品。",
    skills: ["电路综合设计", "焊接调试", "项目报告"],
    prerequisites: ["ei-analog-electronics", "ei-digital-electronics"],
  },
  {
    id: "ei-pcb",
    name: "印刷电路板设计",
    semester: 5,
    credits: 1,
    category: "电路硬件",
    stage: "engineering",
    importance: 4,
    focus: "原理图、PCB 布局布线、制板规范",
    why: "硬件岗位真实要求从原理图走向 PCB 和可制造设计。",
    skills: ["PCB 设计", "器件选型", "硬件规范"],
    prerequisites: ["ei-tech-design"],
  },
  {
    id: "ei-microcomputer",
    name: "微机原理与接口技术",
    semester: 5,
    credits: 2,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 5,
    focus: "微处理器结构、接口控制、总线与外设",
    why: "承接 C、数电和电路，是嵌入式/设备控制方向的主干课。",
    skills: ["接口控制", "底层理解", "外设通信"],
    prerequisites: ["ei-c-language", "ei-digital-electronics"],
  },
  {
    id: "ei-communication",
    name: "通信原理",
    semester: 5,
    credits: 4.5,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "调制、编码、信道、通信系统",
    why: "面向通信工程设计、无线测试和信号处理岗位的核心课程。",
    skills: ["通信系统", "链路分析", "调制编码"],
    prerequisites: ["ei-signals", "ei-probability", "ei-rf"],
  },
  {
    id: "ei-electromagnetic",
    name: "工程电磁场",
    semester: 5,
    credits: 3.5,
    category: "通信感知",
    stage: "engineering",
    importance: 4,
    focus: "电磁场、电磁波、工程电磁应用",
    why: "支撑射频、天线、EMC 和无线通信理解。",
    skills: ["电磁分析", "EMC 意识", "无线传播"],
    prerequisites: ["ei-calculus-2"],
  },
  {
    id: "ei-mcu",
    name: "单片机原理及应用",
    semester: 5,
    credits: 2.5,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 5,
    focus: "单片机 I/O、中断、定时器、外设接口",
    why: "对应真实岗位中的 STM32/MCU 固件、传感器控制和板级调试。",
    skills: ["单片机", "外设接口", "板级调试"],
    prerequisites: ["ei-c-language", "ei-microcomputer"],
  },
  {
    id: "ei-comm-budget",
    name: "通信工程设计和概预算",
    semester: 5,
    credits: 1.5,
    category: "项目实践",
    stage: "practice",
    importance: 3,
    focus: "通信工程方案、图纸、概预算和工程文档",
    why: "面向通信工程实施、项目管理和技术支持岗位。",
    skills: ["工程设计", "概预算", "技术文档"],
    prerequisites: ["ei-communication"],
  },
  {
    id: "ei-dsp",
    name: "数字信号处理技术",
    semester: 6,
    credits: 3.5,
    category: "通信感知",
    stage: "engineering",
    importance: 5,
    focus: "采样、滤波、FFT、数字系统",
    why: "通信、音视频、雷达、传感数据和算法仿真岗位都依赖 DSP 能力。",
    skills: ["DSP", "滤波", "频谱分析"],
    prerequisites: ["ei-signals", "ei-matlab"],
  },
  {
    id: "ei-sensor",
    name: "传感器原理及应用",
    semester: 6,
    credits: 2.5,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "传感器机理、信号采集、测量应用",
    why: "智能硬件、电子设备和测试岗位都需要传感器选型和数据采集能力。",
    skills: ["传感器选型", "数据采集", "信号调理"],
    prerequisites: ["ei-analog-electronics", "ei-mcu"],
  },
  {
    id: "ei-miniprogram",
    name: "基于 Cursor 的微信小程序开发",
    semester: 6,
    credits: 1,
    category: "数据与应用",
    stage: "software",
    importance: 3,
    focus: "AI 辅助开发、小程序界面、接口调用",
    why: "25 版方案新增融合课程，面向轻量应用、设备展示和 AI 工具链使用。",
    skills: ["AI 辅助开发", "小程序", "接口调用"],
    prerequisites: ["ei-python", "ei-data-structure"],
  },
  {
    id: "ei-mcu-practice",
    name: "单片机工程实践",
    semester: 7,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "单片机项目、外设联调、工程实现",
    why: "把 MCU、传感器和电路调试能力沉淀成作品。",
    skills: ["MCU 项目", "外设联调", "工程记录"],
    prerequisites: ["ei-mcu", "ei-sensor"],
  },
  {
    id: "ei-smart-hardware",
    name: "智能硬件电路设计",
    semester: 7,
    credits: 3,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "智能硬件方案、电路设计、系统集成",
    why: "25 版方案的融合实践重点，直接连接电子设备研发和智能系统设计岗位。",
    skills: ["智能硬件", "系统集成", "方案实现"],
    prerequisites: ["ei-pcb", "ei-mcu-practice", "ei-sensor"],
  },
  {
    id: "ei-ai-agent",
    name: "AI 智能体应用与部署",
    semester: 7,
    credits: 1,
    category: "数据与应用",
    stage: "software",
    importance: 4,
    focus: "AI 智能体、应用部署、工程工具链",
    why: "符合 25 版方案的 AI 融合趋势，适合技术支持、数据分析和智能系统方向加分。",
    skills: ["AI 工具链", "应用部署", "智能体"],
    prerequisites: ["ei-ai-basic", "ei-python", "ei-miniprogram"],
  },
  {
    id: "ei-ai-pattern",
    name: "人工智能与模式识别导论",
    semester: 7,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 4,
    focus: "机器学习基础、模式识别、数据特征",
    why: "面向智能检测、信号识别和数据分析岗位的 AI 入门能力。",
    skills: ["机器学习", "模式识别", "特征分析"],
    prerequisites: ["ei-linear-algebra", "ei-probability", "ei-python"],
  },
  {
    id: "ei-thesis",
    name: "毕业论文（设计）",
    semester: "7-8",
    credits: 12,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "选题论证、工程设计、实验分析、论文写作",
    why: "把电子设备、通信系统或智能硬件项目沉淀成可答辩成果。",
    skills: ["工程实现", "实验分析", "论文写作"],
    prerequisites: ["ei-smart-hardware"],
  },
  {
    id: "ei-internship",
    name: "毕业实习",
    semester: 8,
    credits: 7,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "企业岗位、真实项目、职业规范",
    why: "3.5+0.5 培养模式的出口环节，用企业任务检验岗位适应能力。",
    skills: ["岗位适应", "工程协作", "职业规范"],
    prerequisites: ["ei-smart-hardware", "ei-thesis"],
  }
];

export const electronicInfoCareerRoles: CareerRole[] = [
  {
    id: "ei-hardware",
    title: "电子硬件/测试工程师",
    fit: "面向电子设备研发、硬件测试、板级调试岗位，真实招聘更看重仪器、PCB、测试报告和故障闭环。",
    demand: [
      "能读懂原理图和 PCB，理解电源、模拟/数字电路、接口和传感器信号链",
      "熟悉 Altium Designer/嘉立创 EDA、万用表、示波器、信号源、逻辑分析仪",
      "能完成电路调试、焊接返修、测试用例、测试报告和异常复现",
      "了解 EMC/ESD、温升、电源纹波、可靠性验证等量产测试项"
    ],
    courseIds: ["ei-circuit", "ei-analog-electronics", "ei-digital-electronics", "ei-circuit-sim", "ei-tech-design", "ei-pcb", "ei-sensor", "ei-smart-hardware"],
  },
  {
    id: "ei-embedded",
    title: "嵌入式/智能硬件工程师",
    fit: "面向 MCU 固件、智能硬件、设备控制岗位，核心是把 C 程序、外设和传感器跑在真实板子上。",
    demand: [
      "熟练 C/C++，理解 STM32/ESP32/Cortex-M、寄存器和外设时序",
      "熟悉 UART、SPI、I2C、CAN、PWM、ADC、定时器、中断等常见接口",
      "会用 Keil/STM32CubeIDE/GCC、Git、J-Link/ST-Link、串口工具和示波器调试",
      "了解 MQTT/Modbus/TCP/IP、传感器采集、低功耗和设备联调更有竞争力"
    ],
    courseIds: ["ei-c-language", "ei-c-practice", "ei-digital-electronics", "ei-microcomputer", "ei-mcu", "ei-sensor", "ei-mcu-practice", "ei-smart-hardware"],
  },
  {
    id: "ei-communication",
    title: "通信/信号处理工程师",
    fit: "面向通信工程设计、信号处理、测试仿真岗位，要求能建模、仿真、解释波形和频谱。",
    demand: [
      "掌握信号与系统、通信原理、DSP、采样、滤波、调制、信道和频谱分析",
      "熟悉 MATLAB/Simulink 或 Python/Numpy/Scipy，能做算法仿真和数据可视化",
      "了解射频链路、频谱仪、矢量信号源、示波器和通信测试流程",
      "加分项：FPGA/DSP、Verilog/VHDL、无线协议、雷达/声学/图像信号处理场景"
    ],
    courseIds: ["ei-calculus-2", "ei-linear-algebra", "ei-probability", "ei-signals", "ei-rf", "ei-communication", "ei-matlab", "ei-dsp", "ei-comm-budget"],
  },
  {
    id: "ei-ai-system",
    title: "智能系统/AI 工具应用工程师",
    fit: "面向智能检测、数据分析、AI 辅助开发和智能体应用岗位，适合把电子信息和 AI 工具链结合起来的学生。",
    demand: [
      "掌握 Python、数据处理、接口调用和基础机器学习/模式识别概念",
      "能使用 Cursor/AI 编程工具提高开发效率，理解提示词、代码审查和部署流程",
      "了解小程序、Web API、数据库或可视化界面，能把硬件数据做成可展示应用",
      "能完成 AI 智能体应用部署、技术文档、演示 Demo 和项目汇报"
    ],
    courseIds: ["ei-ai-basic", "ei-python", "ei-data-structure", "ei-miniprogram", "ei-ai-agent", "ei-ai-pattern", "ei-smart-hardware"],
  },
  {
    id: "ei-postgraduate",
    title: "考研/升学备考",
    fit: "面向电子信息、通信工程、控制工程、集成电路、仪器科学等方向，重点看数学、英语政治和目标院校专业课。",
    demand: [
      "数学：高数、线代、概率要长期复盘，重视建模和计算准确性",
      "公共课：英语 AⅠ-Ⅲ、政治理论课程要提前积累阅读、翻译和材料分析",
      "专业课：电路、信号与系统、通信原理、数字信号处理按目标院校重点强化",
      "复试/科研：MATLAB/Python 仿真、毕业设计、科技论文写作能支撑项目表达"
    ],
    courseIds: ["ei-calculus-1", "ei-calculus-2", "ei-linear-algebra", "ei-probability", "ei-english-1", "ei-english-2", "ei-english-3", "ei-circuit", "ei-signals", "ei-communication", "ei-dsp", "ei-matlab", "ei-thesis"],
  },
];

export const mobileInternetStats = [
  { label: "毕业总学分", value: "170", note: "25 版培养方案要求" },
  { label: "实践教学", value: "1022", note: "实践学时，软件项目导向" },
  { label: "培养模式", value: "3+1", note: "校内理论 + 企业实训实习" },
  { label: "专业方向", value: "Mobile", note: "移动终端、Web 与互联网软件" },
];

export const mobileInternetCourses: Course[] = [
  {
    id: "mi-english-1",
    name: "大学英语 AⅠ",
    semester: 1,
    credits: 3,
    category: "通用素养",
    stage: "foundation",
    importance: 4,
    focus: "英语阅读、表达和技术资料理解",
    why: "移动开发文档、框架资料和考研英语都需要长期英语积累。",
    skills: ["英语阅读", "文档理解", "表达能力"],
    prerequisites: [],
  },
  {
    id: "mi-calculus-1",
    name: "高等数学 AⅠ",
    semester: 1,
    credits: 5,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "微积分、函数与工程建模基础",
    why: "为算法、信号课程、数据分析和考研数学打底。",
    skills: ["数学建模", "工程计算", "逻辑推导"],
    prerequisites: [],
  },
  {
    id: "mi-ai-basic",
    name: "计算机与人工智能基础",
    semester: 1,
    credits: 1,
    category: "编程基础",
    stage: "foundation",
    importance: 4,
    focus: "计算机基础、AI 基础、数字化工具使用",
    why: "移动互联网岗位越来越依赖 AI 辅助开发、自动化工具和数据意识。",
    skills: ["计算思维", "AI 认知", "工具使用"],
    prerequisites: [],
  },
  {
    id: "mi-python",
    name: "Python 语言程序设计",
    semester: 2,
    credits: 1.5,
    category: "编程基础",
    stage: "software",
    importance: 4,
    focus: "Python 语法、脚本、数据处理",
    why: "适合做测试脚本、数据处理、自动化辅助和 AI 工具链入口。",
    skills: ["Python", "自动化脚本", "数据处理"],
    prerequisites: ["mi-ai-basic"],
  },
  {
    id: "mi-english-2",
    name: "大学英语 AⅡ",
    semester: 2,
    credits: 3,
    category: "通用素养",
    stage: "foundation",
    importance: 4,
    focus: "英语阅读、写作和技术资料理解",
    why: "承接大学英语 AⅠ，继续为技术文档阅读和考研英语打基础。",
    skills: ["英语阅读", "翻译表达", "长期复习"],
    prerequisites: ["mi-english-1"],
  },
  {
    id: "mi-mental-health",
    name: "大学生心理健康教育",
    semester: 2,
    credits: 2,
    category: "通用素养",
    stage: "foundation",
    importance: 1,
    focus: "心理健康、自我调节和压力管理",
    why: "软件项目开发节奏快，心理韧性和自我调节也很重要。",
    skills: ["压力管理", "自我认知"],
    prerequisites: [],
  },
  {
    id: "mi-electronic-training",
    name: "电子实训",
    semester: 2,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 3,
    focus: "基础电子制作、焊接、调试",
    why: "虽然本方向偏软件，但电子信息底色仍要求基本硬件实践。",
    skills: ["焊接", "基础调试", "工程记录"],
    prerequisites: ["mi-circuit"],
  },
  {
    id: "mi-c-language",
    name: "C 语言程序设计",
    semester: 2,
    credits: 2.5,
    category: "编程基础",
    stage: "foundation",
    importance: 4,
    focus: "C 语言、指针、结构体、过程化程序设计",
    why: "支撑计算机基础、微机接口、底层理解和考研计算机方向。",
    skills: ["C 语言", "调试思维", "底层理解"],
    prerequisites: [],
  },
  {
    id: "mi-circuit",
    name: "电路分析",
    semester: 2,
    credits: 4,
    category: "电路硬件",
    stage: "engineering",
    importance: 3,
    focus: "电路定律、频域分析、实验测量",
    why: "保留电子信息基础，让学生理解移动设备和终端硬件环境。",
    skills: ["电路基础", "仪器测量", "工程理解"],
    prerequisites: ["mi-calculus-1"],
  },
  {
    id: "mi-html5-lab",
    name: "HTML5 移动 Web 开发技术实验",
    semester: 2,
    credits: 1,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "HTML5、CSS、移动页面适配、基础交互",
    why: "移动互联网前端岗位的第一层能力，是 Vue、小程序和 Hybrid App 的入口。",
    skills: ["HTML5", "CSS", "移动适配"],
    prerequisites: [],
  },
  {
    id: "mi-photoshop",
    name: "Photoshop 图像处理",
    semester: 2,
    credits: 1,
    category: "通用素养",
    stage: "software",
    importance: 3,
    focus: "图像处理、切图、视觉素材基础",
    why: "适合移动端 UI 切图、运营素材和与设计协作的基础能力。",
    skills: ["图像处理", "视觉协作", "素材处理"],
    prerequisites: [],
  },
  {
    id: "mi-data-structure",
    name: "数据结构",
    semester: 3,
    credits: 2,
    category: "编程基础",
    stage: "software",
    importance: 5,
    focus: "线性表、树、图、查找与排序",
    why: "支撑 Java 后端、移动端性能、算法题和考研专业课。",
    skills: ["算法思维", "复杂度分析", "数据组织"],
    prerequisites: ["mi-c-language"],
  },
  {
    id: "mi-english-3",
    name: "大学英语 AⅢ（新工科）",
    semester: 3,
    credits: 2,
    category: "通用素养",
    stage: "foundation",
    importance: 4,
    focus: "新工科英语、技术资料阅读和表达",
    why: "服务英文技术文档、开源项目资料和考研英语。",
    skills: ["技术英语", "文档阅读", "表达能力"],
    prerequisites: ["mi-english-2"],
  },
  {
    id: "mi-probability",
    name: "概率论与数理统计",
    semester: 3,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "随机变量、统计推断、误差分析",
    why: "服务数据分析、A/B 测试、推荐/用户行为分析和考研数学。",
    skills: ["统计分析", "数据解释", "误差判断"],
    prerequisites: ["mi-calculus-1"],
  },
  {
    id: "mi-complex-functions",
    name: "复变函数与积分变换",
    semester: 3,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 3,
    focus: "复变函数、积分变换和工程数学工具",
    why: "服务信号、通信和考研电子信息方向。",
    skills: ["工程数学", "变换思维"],
    prerequisites: ["mi-calculus-1"],
  },
  {
    id: "mi-java-core",
    name: "Java 核心技术",
    semester: 3,
    credits: 2.5,
    category: "编程基础",
    stage: "software",
    importance: 5,
    focus: "Java、面向对象、集合、异常、基础工程结构",
    why: "Android、Java Web、后端接口和企业应用岗位都需要 Java 基础。",
    skills: ["Java", "OOP", "集合框架"],
    prerequisites: ["mi-c-language", "mi-data-structure"],
  },
  {
    id: "mi-linux",
    name: "Linux 操作系统基础",
    semester: 3,
    credits: 2,
    category: "编程基础",
    stage: "software",
    importance: 5,
    focus: "Linux 命令、文件、进程、服务基础",
    why: "后端部署、移动应用服务端、测试和运维都离不开 Linux。",
    skills: ["Linux", "命令行", "服务排障"],
    prerequisites: ["mi-python"],
  },
  {
    id: "mi-java-core-lab",
    name: "Java 核心技术实验",
    semester: 3,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "Java 项目、集合、异常、面向对象实验",
    why: "把 Java 语法变成可运行项目，是 Android 和后端接口的关键过渡。",
    skills: ["Java 实战", "OOP", "调试"],
    prerequisites: ["mi-java-core"],
  },
  {
    id: "mi-signals",
    name: "信号与系统",
    semester: 3,
    credits: 4,
    category: "通信感知",
    stage: "engineering",
    importance: 3,
    focus: "信号分析、系统响应、频域基础",
    why: "保留电子信息底色，也支撑通信原理和移动通信理解。",
    skills: ["信号分析", "频域思维", "系统建模"],
    prerequisites: ["mi-calculus-1"],
  },
  {
    id: "mi-mysql",
    name: "MySQL 数据库系统",
    semester: 4,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "SQL、表结构、查询、数据库实验",
    why: "真实移动互联网项目都需要用户、订单、内容、日志等数据存储能力。",
    skills: ["SQL", "MySQL", "数据建模"],
    prerequisites: ["mi-data-structure"],
  },
  {
    id: "mi-analog-electronics",
    name: "模拟电子技术",
    semester: 4,
    credits: 4,
    category: "电路硬件",
    stage: "engineering",
    importance: 3,
    focus: "放大电路、运放、模拟信号处理",
    why: "保留电子信息基础，帮助理解移动终端和电子设备硬件环境。",
    skills: ["模拟电路", "信号调理"],
    prerequisites: ["mi-circuit"],
  },
  {
    id: "mi-matlab",
    name: "计算方法与 MATLAB 应用",
    semester: 4,
    credits: 3,
    category: "通信感知",
    stage: "engineering",
    importance: 3,
    focus: "数值计算、MATLAB 仿真和工程数据处理",
    why: "服务信号、通信、数据分析和考研电子信息方向。",
    skills: ["MATLAB", "数值计算", "仿真"],
    prerequisites: ["mi-probability"],
  },
  {
    id: "mi-mysql-lab",
    name: "MySQL 数据库系统实验",
    semester: 4,
    credits: 0.5,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "SQL 实操、表设计、数据维护",
    why: "数据库岗位能力必须经过实操，而不是只会概念。",
    skills: ["SQL 实操", "数据维护", "表设计"],
    prerequisites: ["mi-mysql"],
  },
  {
    id: "mi-js-mobile",
    name: "JS 移动 Web 开发技术实践",
    semester: 4,
    credits: 2,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "JavaScript、DOM、移动端交互、接口调用",
    why: "前端、小程序、H5 活动页和 Hybrid 应用都需要 JS 能力。",
    skills: ["JavaScript", "移动交互", "接口调用"],
    prerequisites: ["mi-html5-lab"],
  },
  {
    id: "mi-microcomputer",
    name: "微机原理与接口技术",
    semester: 4,
    credits: 2,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 3,
    focus: "微机结构、接口、底层通信",
    why: "帮助学生理解移动终端和电子设备底层，不作为本方向就业主线。",
    skills: ["接口理解", "底层通信", "系统结构"],
    prerequisites: ["mi-c-language"],
  },
  {
    id: "mi-jquery",
    name: "JQuery 移动 Web 开发技术",
    semester: 5,
    credits: 1,
    category: "数据与应用",
    stage: "software",
    importance: 3,
    focus: "JQuery、移动页面效果、兼容性处理",
    why: "课程偏传统，但能补充 DOM 操作和历史项目维护能力。",
    skills: ["DOM 操作", "页面交互", "兼容处理"],
    prerequisites: ["mi-js-mobile"],
  },
  {
    id: "mi-ethics-project",
    name: "工程伦理与项目管理",
    semester: 5,
    credits: 2,
    category: "通用素养",
    stage: "practice",
    importance: 3,
    focus: "工程伦理、项目管理、成本与风险意识",
    why: "移动互联网项目涉及隐私、数据、版权和上线风险，需要项目管理意识。",
    skills: ["项目管理", "工程伦理", "风险意识"],
    prerequisites: [],
  },
  {
    id: "mi-electromagnetic",
    name: "工程电磁场",
    semester: 5,
    credits: 3,
    category: "通信感知",
    stage: "engineering",
    importance: 2,
    focus: "电磁场、电磁波和工程应用",
    why: "属于电子信息基础，服务通信和硬件理解。",
    skills: ["电磁分析", "无线传播"],
    prerequisites: [],
  },
  {
    id: "mi-rf",
    name: "高频电子线路",
    semester: 5,
    credits: 3,
    category: "通信感知",
    stage: "engineering",
    importance: 3,
    focus: "高频放大、调制解调、无线链路基础",
    why: "帮助理解移动通信和无线设备的硬件链路。",
    skills: ["射频基础", "调制解调"],
    prerequisites: ["mi-analog-electronics", "mi-signals"],
  },
  {
    id: "mi-java-web",
    name: "Java Web 程序设计实验",
    semester: 5,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "Java Web、接口、服务端业务、数据库联动",
    why: "移动端岗位往往需要懂接口，后端岗位则以 Java Web/Spring 生态为核心。",
    skills: ["Java Web", "REST API", "后端业务"],
    prerequisites: ["mi-java-core", "mi-mysql"],
  },
  {
    id: "mi-dsp",
    name: "数字信号处理技术",
    semester: 5,
    credits: 3,
    category: "通信感知",
    stage: "engineering",
    importance: 3,
    focus: "采样、滤波、频谱分析",
    why: "电子信息基础课程，可支撑音视频、传感数据和考研方向。",
    skills: ["DSP", "滤波", "频谱分析"],
    prerequisites: ["mi-signals"],
  },
  {
    id: "mi-mcu",
    name: "单片机原理及应用",
    semester: 5,
    credits: 3,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 3,
    focus: "单片机外设、中断、接口控制",
    why: "作为电子信息底色课程，帮助理解移动设备与智能控制软件关系。",
    skills: ["MCU", "外设接口", "底层控制"],
    prerequisites: ["mi-c-language", "mi-microcomputer"],
  },
  {
    id: "mi-apps",
    name: "Apps 安装与应用",
    semester: 5,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 2,
    focus: "移动应用生态、安装、配置和应用体验",
    why: "补充移动端应用生态认知，适合产品和测试方向。",
    skills: ["应用体验", "移动生态", "配置管理"],
    prerequisites: ["mi-html5-lab"],
  },
  {
    id: "mi-it-new-tech",
    name: "IT 新技术",
    semester: 5,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 3,
    focus: "行业新技术、工具链和移动互联网趋势",
    why: "移动互联网技术变化快，需要持续跟踪新框架、新平台和 AI 工具。",
    skills: ["技术跟踪", "工具认知", "行业判断"],
    prerequisites: ["mi-ai-basic"],
  },
  {
    id: "mi-objective-c",
    name: "Objective-C 编程",
    semester: 5,
    credits: 1.5,
    category: "编程基础",
    stage: "software",
    importance: 2,
    focus: "Objective-C 语法和 iOS 历史项目维护基础",
    why: "课程偏传统，但可帮助理解 iOS 旧项目维护和移动端语言生态。",
    skills: ["Objective-C", "iOS 旧项目", "语言迁移"],
    prerequisites: ["mi-c-language"],
  },
  {
    id: "mi-communication",
    name: "通信原理",
    semester: 6,
    credits: 3,
    category: "通信感知",
    stage: "iot",
    importance: 3,
    focus: "调制、信道、通信系统",
    why: "让学生理解移动通信和网络连接的工程背景。",
    skills: ["通信系统", "链路分析", "无线理解"],
    prerequisites: ["mi-signals"],
  },
  {
    id: "mi-android-ui",
    name: "Android 图形界面编程与实践",
    semester: 6,
    credits: 2,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "Android UI、页面、组件、交互",
    why: "移动端应用岗位的核心实践课程。",
    skills: ["Android UI", "页面交互", "组件开发"],
    prerequisites: ["mi-java-core"],
  },
  {
    id: "mi-sensor",
    name: "传感器原理及应用",
    semester: 6,
    credits: 3,
    category: "通信感知",
    stage: "iot",
    importance: 3,
    focus: "传感器机理、采集和应用",
    why: "拓展移动互联网与智能设备、可穿戴设备、IoT 应用的连接。",
    skills: ["传感器", "数据采集", "智能设备"],
    prerequisites: ["mi-mcu", "mi-analog-electronics"],
  },
  {
    id: "mi-android-comm",
    name: "Android 通讯技术开发与实践",
    semester: 6,
    credits: 2,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "网络请求、接口联调、通讯模块",
    why: "真实 App 需要稳定连接服务端，接口联调是移动端核心工作。",
    skills: ["HTTP", "接口联调", "网络通信"],
    prerequisites: ["mi-android-ui", "mi-java-web"],
  },
  {
    id: "mi-android-storage",
    name: "Android 移动存储开发与实验",
    semester: 6,
    credits: 2,
    category: "数据与应用",
    stage: "software",
    importance: 4,
    focus: "本地存储、数据库、缓存和状态管理",
    why: "App 的离线、缓存、用户状态和性能优化都依赖存储能力。",
    skills: ["本地存储", "缓存", "状态管理"],
    prerequisites: ["mi-android-ui", "mi-mysql"],
  },
  {
    id: "mi-harmonyos",
    name: "HarmonyOS 开发与实践",
    semester: 6,
    credits: 2,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "HarmonyOS、ArkTS/ArkUI、鸿蒙应用开发",
    why: "近年鸿蒙岗位增长明显，ArkTS/ArkUI 是移动互联网方向必须关注的新生态。",
    skills: ["HarmonyOS", "ArkTS", "ArkUI"],
    prerequisites: ["mi-java-core", "mi-js-mobile"],
  },
  {
    id: "mi-android-commerce",
    name: "Android 移动商务项目实现",
    semester: 6,
    credits: 2,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "移动商务 App、业务流程、项目实现",
    why: "将 UI、接口、存储、业务逻辑串成完整作品。",
    skills: ["App 项目", "业务流程", "项目交付"],
    prerequisites: ["mi-android-ui", "mi-android-comm", "mi-android-storage"],
  },
  {
    id: "mi-vue",
    name: "Vue 移动 Web 开发技术实验",
    semester: 6,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 5,
    focus: "Vue、组件化、移动 Web 应用",
    why: "当前前端招聘主流仍是 Vue/React + TypeScript，小程序和 H5 都可承接。",
    skills: ["Vue", "组件化", "移动 Web"],
    prerequisites: ["mi-js-mobile", "mi-mysql"],
  },
  {
    id: "mi-android-game",
    name: "Android 游戏开发实践",
    semester: 6,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 3,
    focus: "Android 游戏场景、交互、动画和性能意识",
    why: "补充移动端高交互场景，适合前端/客户端性能和交互能力训练。",
    skills: ["游戏交互", "动画", "性能意识"],
    prerequisites: ["mi-android-ui"],
  },
  {
    id: "mi-4g-app",
    name: "互联网移动 4G APP 开发",
    semester: 6,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 3,
    focus: "移动网络场景、App 通信和业务开发",
    why: "虽然 4G 表述偏旧，但对应移动网络应用和接口稳定性训练。",
    skills: ["移动网络", "App 通信", "业务开发"],
    prerequisites: ["mi-android-comm"],
  },
  {
    id: "mi-mobile-big-data",
    name: "移动大数据",
    semester: 6,
    credits: 1.5,
    category: "数据与应用",
    stage: "software",
    importance: 4,
    focus: "移动用户数据、行为分析和数据应用",
    why: "市场中的数据分析、产品、运营和推荐场景都需要数据意识。",
    skills: ["数据分析", "用户行为", "指标意识"],
    prerequisites: ["mi-mysql", "mi-probability"],
  },
  {
    id: "mi-literature-writing",
    name: "文献检索与科技论文写作",
    semester: 6,
    credits: 1,
    category: "通用素养",
    stage: "practice",
    importance: 3,
    focus: "文献检索、技术写作和论文表达",
    why: "服务毕业设计、考研复试和技术文档表达。",
    skills: ["文献检索", "技术写作", "论文表达"],
    prerequisites: ["mi-enterprise-training"],
  },
  {
    id: "mi-enterprise-training",
    name: "企业实训：移动互联技术岗位综合实训",
    semester: 7,
    credits: 8,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "企业项目、团队协作、移动互联网综合交付",
    why: "这是本方向从课程到真实岗位的关键出口，适合沉淀作品集。",
    skills: ["综合项目", "团队协作", "工程交付"],
    prerequisites: ["mi-android-commerce", "mi-vue", "mi-harmonyos", "mi-java-web"],
  },
  {
    id: "mi-thesis",
    name: "毕业论文（设计）",
    semester: 8,
    credits: 12,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "选题、系统设计、实现、测试、论文写作",
    why: "将移动互联网项目沉淀为可答辩、可展示、可写进简历的成果。",
    skills: ["系统设计", "项目实现", "论文写作"],
    prerequisites: ["mi-enterprise-training"],
  },
  {
    id: "mi-linux-c-control",
    name: "基于 Linux+C 的智能控制软件设计",
    semester: 7,
    credits: 1.5,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 3,
    focus: "Linux+C、控制软件、设备端逻辑",
    why: "连接移动互联网与智能设备控制，适合 IoT/嵌入式软件交叉方向。",
    skills: ["Linux C", "控制软件", "设备端逻辑"],
    prerequisites: ["mi-linux", "mi-c-language", "mi-mcu"],
  },
  {
    id: "mi-internship",
    name: "毕业实习：综合岗位实习",
    semester: 8,
    credits: 2,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "企业岗位、综合任务、职业规范",
    why: "3+1 模式的真实岗位适应环节。",
    skills: ["岗位适应", "沟通协作", "交付意识"],
    prerequisites: ["mi-enterprise-training"],
  }
];

export const mobileInternetCareerRoles: CareerRole[] = [
  {
    id: "mi-android",
    title: "Android / 鸿蒙移动端开发",
    fit: "面向 App、鸿蒙应用、移动端业务开发岗位。真实市场已从单纯 Java Android 转向 Kotlin/Jetpack 与 HarmonyOS 并行。",
    demand: [
      "掌握 Java/Kotlin，熟悉 Android Studio、Activity/Fragment、生命周期、权限和多线程",
      "熟悉 Jetpack、MVVM、Room、Retrofit/OkHttp、协程/Flow，了解 Jetpack Compose 更加分",
      "掌握接口联调、JSON、登录鉴权、缓存、本地存储、弱网处理和性能优化",
      "关注 HarmonyOS NEXT，了解 ArkTS、ArkUI、DevEco Studio 和鸿蒙应用发布流程"
    ],
    courseIds: ["mi-java-core", "mi-android-ui", "mi-android-comm", "mi-android-storage", "mi-harmonyos", "mi-android-commerce", "mi-enterprise-training"],
  },
  {
    id: "mi-frontend",
    title: "前端 / 小程序 / 移动 Web 开发",
    fit: "面向 H5、管理后台、小程序、移动 Web、混合应用岗位。市场主流是 Vue/React + TypeScript + 工程化。",
    demand: [
      "掌握 HTML5、CSS3、JavaScript/TypeScript、ES6+、移动端适配和浏览器兼容",
      "熟悉 Vue3/React、组件化、状态管理、路由、Vite/Webpack 和接口联调",
      "了解微信小程序、uni-app/Taro、Hybrid App、H5 活动页和跨端开发场景",
      "具备 Git 协作、UI 还原、性能优化、埋点、错误监控和基础测试意识"
    ],
    courseIds: ["mi-html5-lab", "mi-js-mobile", "mi-jquery", "mi-vue", "mi-mysql", "mi-java-web", "mi-enterprise-training"],
  },
  {
    id: "mi-backend",
    title: "Java 后端 / 接口开发",
    fit: "面向移动 App 服务端、业务接口、管理后台和企业软件开发岗位。移动互联网学生要懂客户端，也要懂接口从哪来。",
    demand: [
      "掌握 Java、面向对象、集合、多线程基础，熟悉 Spring Boot/Spring MVC 更有竞争力",
      "熟悉 MySQL、SQL 优化、事务、索引，了解 Redis、缓存、消息队列和 RESTful API",
      "会 Linux、Git、Maven/Gradle、接口文档、Postman/Apifox 和日志排查",
      "了解 Docker、Nginx、微服务、鉴权、接口安全和部署流程"
    ],
    courseIds: ["mi-java-core", "mi-linux", "mi-mysql", "mi-java-web", "mi-python", "mi-enterprise-training"],
  },
  {
    id: "mi-test",
    title: "移动端测试 / 软件测试工程师",
    fit: "面向 App 测试、Web 测试、接口测试和企业项目测试岗位。市场对初级岗位更看重测试方法和工具熟练度。",
    demand: [
      "掌握功能测试、兼容性测试、回归测试、测试用例、缺陷管理和测试报告",
      "会 Postman/Apifox 做接口测试，能读懂 HTTP、JSON、状态码和接口文档",
      "了解 Appium、Selenium、JMeter、抓包工具、日志分析和自动化测试脚本",
      "熟悉 Android/iOS/HarmonyOS 基础使用场景，能定位前端、后端、网络或数据问题"
    ],
    courseIds: ["mi-python", "mi-html5-lab", "mi-mysql", "mi-android-ui", "mi-android-comm", "mi-vue", "mi-enterprise-training", "mi-internship"],
  },
  {
    id: "mi-product",
    title: "互联网产品 / 项目实施助理",
    fit: "适合技术理解不错、表达和沟通更强的学生。岗位不要求写最多代码，但要求懂业务、懂数据、懂交付。",
    demand: [
      "能写需求文档、流程图、原型说明、验收标准，理解移动端和 Web 基本实现方式",
      "熟悉 Axure/Figma/墨刀、Excel、SQL 基础、数据看板和用户反馈整理",
      "能和开发、测试、客户沟通，推动版本迭代、问题闭环和项目交付",
      "了解互联网项目管理、敏捷协作、埋点分析、A/B 测试和上线流程"
    ],
    courseIds: ["mi-photoshop", "mi-mysql", "mi-js-mobile", "mi-android-commerce", "mi-enterprise-training", "mi-thesis", "mi-internship"],
  },
  {
    id: "mi-postgraduate",
    title: "考研/升学备考",
    fit: "移动互联网方向可考电子信息、计算机技术、软件工程、人工智能相关方向，专业课选择差异会很大。",
    demand: [
      "数学：高数、线代、概率要长期复盘，尤其重视计算准确性和题型训练",
      "计算机方向：重点补数据结构、C/Java、操作系统、数据库和网络基础",
      "电子信息方向：电路、信号与系统、通信原理、数字信号处理按目标院校强化",
      "复试项目：企业实训、Android/Vue/Java Web 项目和毕业设计要能讲清架构与实现"
    ],
    courseIds: ["mi-calculus-1", "mi-data-structure", "mi-c-language", "mi-java-core", "mi-linux", "mi-mysql", "mi-signals", "mi-communication", "mi-thesis"],
  },
];

export const communicationEngineeringStats = [
  { label: "毕业总学分", value: "170", note: "25 版培养方案要求" },
  { label: "实践教学", value: "1142", note: "实践学时，通信工程导向" },
  { label: "培养模式", value: "3+1", note: "校内课程 + 企业实训实习" },
  { label: "专业方向", value: "5G/ICT", note: "移动通信、数据通信、光接入" },
];

export const communicationEngineeringCourses: Course[] = [
  {
    id: "ce-english-1",
    name: "大学英语 AI",
    semester: 1,
    credits: 4,
    category: "通用素养",
    stage: "foundation",
    importance: 2,
    focus: "工程英语阅读、技术资料理解",
    why: "通信设备资料、协议文档和厂商手册大量使用英文，早期打底能降低后续学习门槛。",
    skills: ["英文资料阅读", "术语积累"],
    prerequisites: [],
  },
  {
    id: "ce-ai-basic",
    name: "计算机与人工智能基础",
    semester: 1,
    credits: 1,
    category: "编程基础",
    stage: "foundation",
    importance: 3,
    focus: "计算机基础、AI 概念、数据意识",
    why: "通信岗位正在向智能运维、智能网优和数据分析靠拢，需要先理解计算机系统和数据思维。",
    skills: ["计算机基础", "AI 认知"],
    prerequisites: [],
  },
  {
    id: "ce-calculus-1",
    name: "高等数学 AI",
    semester: 1,
    credits: 5,
    category: "数学建模",
    stage: "foundation",
    importance: 5,
    focus: "函数、极限、微积分基础",
    why: "信号、通信、电磁场、数字信号处理都依赖连续系统和变化率思维。",
    skills: ["数学建模", "连续系统理解"],
    prerequisites: [],
  },
  {
    id: "ce-c-language",
    name: "C 语言程序设计",
    semester: 1,
    credits: 3,
    category: "编程基础",
    stage: "foundation",
    importance: 5,
    focus: "语法、指针、结构体、过程化编程",
    why: "通信设备侧、嵌入式调测、协议栈理解和考研复试都离不开 C 语言基础。",
    skills: ["C 语言", "调试思维", "内存理解"],
    prerequisites: [],
  },
  {
    id: "ce-english-2",
    name: "大学英语 AII",
    semester: 2,
    credits: 4,
    category: "通用素养",
    stage: "foundation",
    importance: 2,
    focus: "技术阅读、表达与翻译",
    why: "继续强化英文文档阅读能力，支撑后续通信协议、设备手册和论文阅读。",
    skills: ["英文阅读", "技术表达"],
    prerequisites: ["ce-english-1"],
  },
  {
    id: "ce-python",
    name: "Python 语言程序设计",
    semester: 2,
    credits: 3,
    category: "编程基础",
    stage: "software",
    importance: 4,
    focus: "脚本、数据处理、自动化",
    why: "网优、运维和测试岗位常用 Python 处理日志、指标、报表和自动化脚本。",
    skills: ["Python", "数据处理", "脚本自动化"],
    prerequisites: ["ce-c-language"],
  },
  {
    id: "ce-calculus-2",
    name: "高等数学 AII",
    semester: 2,
    credits: 5,
    category: "数学建模",
    stage: "foundation",
    importance: 5,
    focus: "多元函数、级数、微分方程",
    why: "为傅里叶分析、信号系统、电磁场和通信理论继续打数学底座。",
    skills: ["多元分析", "微分方程"],
    prerequisites: ["ce-calculus-1"],
  },
  {
    id: "ce-circuit",
    name: "电路分析",
    semester: 2,
    credits: 4,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "电路定律、暂态稳态、频域分析",
    why: "所有通信硬件、射频电路和测试测量都从电路分析开始。",
    skills: ["电路分析", "频域思维"],
    prerequisites: ["ce-calculus-1"],
  },
  {
    id: "ce-linear",
    name: "线性代数",
    semester: 2,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "矩阵、向量空间、线性变换",
    why: "MIMO、信号处理、机器学习和通信算法都大量使用矩阵运算。",
    skills: ["矩阵运算", "线性建模"],
    prerequisites: ["ce-calculus-1"],
  },
  {
    id: "ce-comm-intro",
    name: "通信工程导论",
    semester: 2,
    credits: 1,
    category: "通信感知",
    stage: "iot",
    importance: 3,
    focus: "通信行业、网络架构、岗位地图",
    why: "帮助学生区分无线网优、数据通信、光传输、工程交付和技术支持这些真实岗位方向。",
    skills: ["行业认知", "网络架构"],
    prerequisites: ["ce-ai-basic"],
  },
  {
    id: "ce-english-3",
    name: "大学英语 AIII",
    semester: 3,
    credits: 2,
    category: "通用素养",
    stage: "foundation",
    importance: 2,
    focus: "专业资料阅读、工程表达",
    why: "为专业英语、论文阅读和厂家英文配置手册做过渡。",
    skills: ["工程英语", "资料检索"],
    prerequisites: ["ce-english-2"],
  },
  {
    id: "ce-analog",
    name: "模拟电子技术",
    semester: 3,
    credits: 5,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "二极管、三极管、放大电路、运放",
    why: "射频前端、传感采集、通信设备硬件调试都需要模拟电路底子。",
    skills: ["模拟电路", "放大电路", "仪器调试"],
    prerequisites: ["ce-circuit"],
  },
  {
    id: "ce-probability",
    name: "概率论与数理统计",
    semester: 3,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "随机变量、统计推断、误差分析",
    why: "通信信道、噪声、误码率、网优指标和数据分析都离不开概率统计。",
    skills: ["统计分析", "随机建模"],
    prerequisites: ["ce-calculus-2"],
  },
  {
    id: "ce-data-comm",
    name: "数据通信技术与实验",
    semester: 3,
    credits: 3,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "TCP/IP、交换、路由、网络实验",
    why: "数据通信工程师、ICT 运维和网络交付岗位的直接入口课。",
    skills: ["TCP/IP", "路由交换", "网络实验"],
    prerequisites: ["ce-comm-intro"],
  },
  {
    id: "ce-data-structure",
    name: "数据结构",
    semester: 3,
    credits: 2.5,
    category: "编程基础",
    stage: "software",
    importance: 4,
    focus: "线性表、树、图、查找与排序",
    why: "为通信软件、协议逻辑、脚本效率和考研计算机方向打基础。",
    skills: ["算法思维", "数据组织"],
    prerequisites: ["ce-c-language"],
  },
  {
    id: "ce-complex",
    name: "复变函数与积分变换",
    semester: 3,
    credits: 3,
    category: "数学建模",
    stage: "foundation",
    importance: 4,
    focus: "复数域、积分变换、频域工具",
    why: "信号与系统、通信原理和数字信号处理会大量使用频域分析。",
    skills: ["频域分析", "积分变换"],
    prerequisites: ["ce-calculus-2"],
  },
  {
    id: "ce-pro-english",
    name: "专业英语",
    semester: 3,
    credits: 2,
    category: "通用素养",
    stage: "practice",
    importance: 3,
    focus: "通信术语、设备文档、技术表达",
    why: "厂商设备手册、协议文档、海外资料和英文面试表达都需要专业英语。",
    skills: ["通信英语", "文档阅读"],
    prerequisites: ["ce-english-3", "ce-comm-intro"],
  },
  {
    id: "ce-digital",
    name: "数字电子技术",
    semester: 4,
    credits: 5,
    category: "电路硬件",
    stage: "engineering",
    importance: 5,
    focus: "逻辑门、触发器、组合/时序电路",
    why: "通信设备硬件、接口电路和嵌入式系统都需要数字电路能力。",
    skills: ["数字逻辑", "时序分析"],
    prerequisites: ["ce-analog"],
  },
  {
    id: "ce-matlab",
    name: "计算方法与 MATLAB 应用",
    semester: 4,
    credits: 2,
    category: "数学建模",
    stage: "software",
    importance: 4,
    focus: "数值计算、仿真、曲线分析",
    why: "通信原理、信号处理和网优指标分析常需要仿真与数据可视化。",
    skills: ["MATLAB", "数值仿真"],
    prerequisites: ["ce-linear", "ce-probability"],
  },
  {
    id: "ce-rf",
    name: "高频电子线路",
    semester: 4,
    credits: 2.5,
    category: "通信感知",
    stage: "engineering",
    importance: 5,
    focus: "高频放大、振荡、调制解调",
    why: "无线通信、射频测试、基站设备和通信硬件调试的关键课程。",
    skills: ["射频基础", "调制解调", "仪器测试"],
    prerequisites: ["ce-analog", "ce-circuit"],
  },
  {
    id: "ce-signals",
    name: "信号与系统",
    semester: 4,
    credits: 3,
    category: "通信感知",
    stage: "engineering",
    importance: 5,
    focus: "连续/离散信号、系统响应、频域分析",
    why: "通信原理、数字信号处理、滤波、调制和网优分析的核心前置。",
    skills: ["信号分析", "系统响应", "频域理解"],
    prerequisites: ["ce-complex", "ce-circuit"],
  },
  {
    id: "ce-ptn",
    name: "PTN 分组交换光传输技术",
    semester: 4,
    credits: 2,
    category: "通信感知",
    stage: "iot",
    importance: 4,
    focus: "PTN、分组传送、承载网络",
    why: "光传输、城域网和通信承载网岗位需要理解 PTN/传输网络。",
    skills: ["PTN", "承载网", "传输网络"],
    prerequisites: ["ce-data-comm"],
  },
  {
    id: "ce-em-field",
    name: "工程电磁场",
    semester: 4,
    credits: 2,
    category: "通信感知",
    stage: "engineering",
    importance: 4,
    focus: "电磁场、波传播、边界条件",
    why: "天线、无线覆盖、射频传播和高速通信都依赖电磁场基础。",
    skills: ["电磁场", "波传播"],
    prerequisites: ["ce-calculus-2"],
  },
  {
    id: "ce-data-network-training",
    name: "数据网络组建综合实训",
    semester: 4,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "网络拓扑、交换路由、配置联调",
    why: "把数据通信课落到真实网络配置，是数据通信和 ICT 运维岗位的作品证明。",
    skills: ["网络配置", "联调排障", "拓扑设计"],
    prerequisites: ["ce-data-comm"],
  },
  {
    id: "ce-ptn-lab",
    name: "PTN 分组交换光传输技术实验",
    semester: 4,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "PTN 设备配置、业务开通、故障定位",
    why: "光传输岗位非常看重设备配置与故障定位经验。",
    skills: ["PTN 配置", "业务开通", "故障定位"],
    prerequisites: ["ce-ptn"],
  },
  {
    id: "ce-pcb",
    name: "印刷电路板设计",
    semester: 4,
    credits: 1,
    category: "电路硬件",
    stage: "engineering",
    importance: 3,
    focus: "原理图、PCB 布局布线、制板规范",
    why: "对通信设备硬件测试、样机调试和嵌入式方向有加分作用。",
    skills: ["PCB 设计", "硬件规范"],
    prerequisites: ["ce-digital", "ce-analog"],
  },
  {
    id: "ce-communication",
    name: "通信原理",
    semester: 5,
    credits: 2.5,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "调制、编码、信道、同步、噪声",
    why: "通信方向的专业主干课，决定能否理解无线、光传输和通信系统指标。",
    skills: ["通信系统", "调制编码", "信道分析"],
    prerequisites: ["ce-signals", "ce-probability", "ce-rf"],
  },
  {
    id: "ce-microcomputer",
    name: "微机原理与接口技术",
    semester: 5,
    credits: 4,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 4,
    focus: "微处理器、总线、接口、外设控制",
    why: "通信设备调测、板级接口和嵌入式通信终端需要底层接口能力。",
    skills: ["接口技术", "底层控制", "调试"],
    prerequisites: ["ce-digital", "ce-c-language"],
  },
  {
    id: "ce-5g",
    name: "5G 移动通信技术",
    semester: 5,
    credits: 2,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "5G 架构、无线接入、核心网、典型业务",
    why: "无线网优、基站交付、运营商运维和通信项目都绕不开 5G 网络。",
    skills: ["5G NR", "移动通信架构", "无线接入"],
    prerequisites: ["ce-communication", "ce-data-comm"],
  },
  {
    id: "ce-optical-access",
    name: "光接入技术",
    semester: 5,
    credits: 2,
    category: "通信感知",
    stage: "iot",
    importance: 4,
    focus: "PON、光接入网、光链路指标",
    why: "家宽、园区、运营商接入网和光网络交付岗位的核心技能入口。",
    skills: ["PON", "光链路", "接入网"],
    prerequisites: ["ce-ptn"],
  },
  {
    id: "ce-5g-lab",
    name: "5G 移动通信技术实验",
    semester: 5,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "5G 网络配置、指标观察、业务验证",
    why: "把 5G 概念落到可操作实验，适合支撑网优、测试和运维简历。",
    skills: ["5G 实验", "指标观察", "业务验证"],
    prerequisites: ["ce-5g"],
  },
  {
    id: "ce-optical-lab",
    name: "光接入技术实验",
    semester: 5,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "光功率、链路测试、业务开通",
    why: "光接入工程师需要能看懂光链路指标并完成现场开通与排障。",
    skills: ["光功率测试", "链路排障", "业务开通"],
    prerequisites: ["ce-optical-access"],
  },
  {
    id: "ce-telecom-project",
    name: "电信项目工程实施",
    semester: 5,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "现场勘察、施工组织、开通验收",
    why: "工程交付岗位最看重现场流程、验收资料和问题闭环能力。",
    skills: ["工程实施", "现场交付", "验收资料"],
    prerequisites: ["ce-comm-intro", "ce-data-network-training"],
  },
  {
    id: "ce-optical-training",
    name: "光传输技术综合实训",
    semester: 5,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "光传输组网、业务配置、故障排查",
    why: "这是光传输/接入方向最接近岗位任务的课程，应作为简历项目重点包装。",
    skills: ["光传输组网", "业务配置", "故障排查"],
    prerequisites: ["ce-ptn-lab", "ce-optical-lab"],
  },
  {
    id: "ce-budget-wired",
    name: "通信工程设计和概预算（有线方向）",
    semester: 5,
    credits: 2,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "有线网络设计、工程图纸、概预算",
    why: "通信工程设计、交付和项目助理岗位需要会看图、算量、做预算和写方案。",
    skills: ["工程设计", "概预算", "图纸识读"],
    prerequisites: ["ce-telecom-project", "ce-optical-access"],
  },
  {
    id: "ce-budget-wireless",
    name: "通信工程设计和概预算（无线方向）",
    semester: 5,
    credits: 2,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "无线站点设计、覆盖规划、概预算",
    why: "无线网规网优和基站工程交付岗位需要理解站点、覆盖、容量和投资估算。",
    skills: ["无线规划", "覆盖设计", "概预算"],
    prerequisites: ["ce-5g", "ce-em-field"],
  },
  {
    id: "ce-mcu",
    name: "单片机原理及应用",
    semester: 5,
    credits: 2,
    category: "嵌入式底层",
    stage: "embedded",
    importance: 3,
    focus: "I/O、中断、定时器、串口通信",
    why: "对通信终端、设备侧接口调试和嵌入式技术支持有补强价值。",
    skills: ["单片机", "串口通信", "外设控制"],
    prerequisites: ["ce-c-language", "ce-microcomputer"],
  },
  {
    id: "ce-45g-planning",
    name: "4G/5G 全网规划与部署",
    semester: 6,
    credits: 2,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "无线规划、参数配置、网络部署",
    why: "无线网优、网规、基站开通和运营商网络维护的关键岗位课。",
    skills: ["无线规划", "参数配置", "网络部署"],
    prerequisites: ["ce-5g", "ce-budget-wireless"],
  },
  {
    id: "ce-ict-marketing",
    name: "ICT 系统营销",
    semester: 6,
    credits: 2,
    category: "项目实践",
    stage: "practice",
    importance: 3,
    focus: "ICT 方案、客户需求、售前沟通",
    why: "通信行业大量岗位在解决方案、售前、项目支持侧，需要能把技术讲给客户听。",
    skills: ["ICT 方案", "售前沟通", "需求分析"],
    prerequisites: ["ce-data-comm", "ce-5g"],
  },
  {
    id: "ce-ethics-project",
    name: "工程伦理与项目管理",
    semester: 6,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 4,
    focus: "项目计划、质量、安全、风险",
    why: "通信现场工程涉及安全、质量、进度和验收，项目管理能力会直接影响岗位表现。",
    skills: ["项目管理", "质量意识", "风险控制"],
    prerequisites: ["ce-telecom-project"],
  },
  {
    id: "ce-45g-training",
    name: "4G/5G 全网规划与部署综合实训",
    semester: 6,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "规划仿真、部署联调、指标优化",
    why: "这是无线网优方向最适合沉淀成作品集的实训课程。",
    skills: ["网规网优", "指标优化", "联调排障"],
    prerequisites: ["ce-45g-planning"],
  },
  {
    id: "ce-45g-lab",
    name: "4G/5G 全网规划与部署实验",
    semester: 6,
    credits: 1,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "参数配置、覆盖验证、业务测试",
    why: "无线岗位面试常会问覆盖、切换、参数和指标问题，实验经历能形成可讲案例。",
    skills: ["参数配置", "覆盖验证", "业务测试"],
    prerequisites: ["ce-45g-planning"],
  },
  {
    id: "ce-dsp",
    name: "数字信号处理技术",
    semester: 6,
    credits: 2,
    category: "通信感知",
    stage: "iot",
    importance: 5,
    focus: "采样、滤波、FFT、数字系统",
    why: "通信算法、调制解调、频谱分析和考研通信方向都需要 DSP。",
    skills: ["数字滤波", "FFT", "频谱分析"],
    prerequisites: ["ce-signals", "ce-matlab"],
  },
  {
    id: "ce-literature",
    name: "文献检索与科技论文写作",
    semester: 6,
    credits: 1,
    category: "通用素养",
    stage: "practice",
    importance: 3,
    focus: "论文检索、技术写作、规范表达",
    why: "为毕业设计、考研复试和技术方案写作做准备。",
    skills: ["文献检索", "技术写作"],
    prerequisites: ["ce-pro-english"],
  },
  {
    id: "ce-ai-pattern",
    name: "人工智能与模式识别导论",
    semester: 6,
    credits: 2,
    category: "数据与应用",
    stage: "software",
    importance: 3,
    focus: "模式识别、机器学习、智能分析",
    why: "智能网优、故障预测和通信数据分析会越来越需要 AI 基础。",
    skills: ["机器学习认知", "模式识别", "智能分析"],
    prerequisites: ["ce-python", "ce-probability"],
  },
  {
    id: "ce-enterprise-mobile-training",
    name: "移动通信技术岗位综合实训",
    semester: 7,
    credits: 16,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "企业项目、岗位流程、综合交付",
    why: "3+1 培养模式的岗位适应核心环节，应沉淀为简历项目和面试案例。",
    skills: ["岗位实训", "项目交付", "问题闭环"],
    prerequisites: ["ce-45g-training", "ce-optical-training", "ce-ethics-project"],
  },
  {
    id: "ce-thesis",
    name: "毕业论文（设计）",
    semester: "7-8",
    credits: 12,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "选题论证、系统设计、实验分析、论文写作",
    why: "毕业设计是把课程链路整合成个人技术作品的最后机会。",
    skills: ["系统设计", "实验分析", "论文写作"],
    prerequisites: ["ce-literature", "ce-enterprise-mobile-training"],
  },
  {
    id: "ce-internship",
    name: "毕业实习",
    semester: 8,
    credits: 16,
    category: "项目实践",
    stage: "practice",
    importance: 5,
    focus: "企业岗位、现场流程、职业规范",
    why: "面向运营商、设备商、工程交付和 ICT 运维岗位的真实适应阶段。",
    skills: ["岗位适应", "工程沟通", "现场规范"],
    prerequisites: ["ce-enterprise-mobile-training"],
  }
];

export const communicationEngineeringCareerRoles: CareerRole[] = [
  {
    id: "ce-wireless-optimization",
    title: "5G 无线网络优化工程师",
    fit: "面向运营商、通信服务商、设备商网优交付岗位。真实招聘更看重 LTE/NR 指标理解、路测分析、参数优化和现场沟通。",
    demand: [
      "理解 4G/5G 无线网络架构、覆盖、容量、干扰、切换、接入和掉线等问题定位逻辑",
      "熟悉 DT/CQT、MR、KPI、PCI、邻区、RSRP/RSRQ/SINR、吞吐率等网优常用指标",
      "能使用网优测试软件、地图分析、Excel/Python 处理路测数据和日报周报",
      "具备站点开通、参数核查、投诉处理、现场沟通和问题闭环意识"
    ],
    courseIds: ["ce-c-language", "ce-python", "ce-signals", "ce-rf", "ce-communication", "ce-5g", "ce-budget-wireless", "ce-45g-planning", "ce-45g-training", "ce-dsp", "ce-enterprise-mobile-training"],
  },
  {
    id: "ce-datacom-engineer",
    title: "数据通信 / ICT 网络工程师",
    fit: "面向政企网络、园区网、运营商承载网、ICT 运维和交付岗位。市场主流要求是 TCP/IP + 路由交换 + 设备配置 + 排障。",
    demand: [
      "掌握 TCP/IP、VLAN、STP、OSPF、BGP、ACL、NAT、QoS 等路由交换基础",
      "能配置和排查华为/H3C/Cisco 类交换机、路由器、防火墙和无线网络设备",
      "熟悉 Linux、常见网络命令、抓包、日志分析、IP 地址规划和网络拓扑设计",
      "具备 HCIA/HCIP 或同类证书意识，会写配置文档、割接方案和故障报告"
    ],
    courseIds: ["ce-python", "ce-data-comm", "ce-data-structure", "ce-data-network-training", "ce-ptn", "ce-ptn-lab", "ce-45g-planning", "ce-ict-marketing", "ce-enterprise-mobile-training"],
  },
  {
    id: "ce-optical-access",
    title: "光传输 / 光接入工程师",
    fit: "面向运营商接入网、家宽/政企专线、传输网络工程与维护岗位。岗位关键词集中在 PON、PTN/OTN、光功率、OTDR 和故障处理。",
    demand: [
      "理解光纤通信、PON、PTN/OTN、传输承载网和接入网业务开通流程",
      "会使用光功率计、OTDR 等工具进行链路测试、衰耗判断和故障定位",
      "能完成设备上架、业务配置、专线开通、割接配合、验收资料和现场记录",
      "具备布线规范、安全规范、客户沟通和跨团队协作能力"
    ],
    courseIds: ["ce-ptn", "ce-ptn-lab", "ce-optical-access", "ce-optical-lab", "ce-optical-training", "ce-telecom-project", "ce-budget-wired", "ce-enterprise-mobile-training"],
  },
  {
    id: "ce-project-delivery",
    title: "通信工程实施 / 项目交付工程师",
    fit: "面向基站、室分、传输、政企 ICT 项目实施与交付岗位。这个方向不只看技术，还看图纸、预算、进度、验收和沟通。",
    demand: [
      "熟悉通信工程勘察、设计、施工、开通、验收、资料归档和项目闭环流程",
      "能看懂工程图纸、设备清单、站点资料、概预算和基础施工规范",
      "理解有线、无线、传输、接入网常见设备和现场安全要求",
      "具备客户沟通、项目计划、风险记录、问题协调和交付文档能力"
    ],
    courseIds: ["ce-comm-intro", "ce-pro-english", "ce-telecom-project", "ce-budget-wired", "ce-budget-wireless", "ce-ethics-project", "ce-ict-marketing", "ce-enterprise-mobile-training", "ce-internship"],
  },
  {
    id: "ce-communication-test",
    title: "通信测试 / 技术支持工程师",
    fit: "面向设备测试、现场技术支持、实验室测试和售后支持岗位。要求能读指标、会用仪器、能复现问题并写清楚报告。",
    demand: [
      "理解电路、射频、信号、通信原理和常见通信设备接口",
      "会使用示波器、频谱仪、信号源、万用表等基础测试工具，能记录测试条件和结果",
      "能分析日志、定位软硬件或网络侧问题，推动研发、交付和客户侧协同解决",
      "具备问题复现、测试用例、故障报告、版本验证和客户支持意识"
    ],
    courseIds: ["ce-circuit", "ce-analog", "ce-digital", "ce-rf", "ce-signals", "ce-communication", "ce-dsp", "ce-microcomputer", "ce-5g-lab", "ce-optical-lab", "ce-thesis"],
  },
  {
    id: "ce-postgraduate",
    title: "考研/升学备考",
    fit: "通信方向可考电子信息、通信与信息系统、信号与信息处理、网络空间安全等方向，核心是数学 + 信号通信专业课。",
    demand: [
      "数学主线：高数、线代、概率、复变函数要长期复盘，重视计算准确性和推导能力",
      "专业课主线：电路、信号与系统、通信原理、数字信号处理是通信方向最常见基础",
      "计算机补强：C 语言、数据结构、数据通信能提高复试项目和跨方向竞争力",
      "复试作品：5G 实训、光传输实训、毕业设计要能讲清问题、方案、指标和结果"
    ],
    courseIds: ["ce-calculus-1", "ce-calculus-2", "ce-linear", "ce-probability", "ce-complex", "ce-circuit", "ce-signals", "ce-communication", "ce-dsp", "ce-data-structure", "ce-thesis"],
  },
];

export const curriculumDataByMajor: Record<string, CurriculumDataset> = {
  "electronic-iot": {
    stats: curriculumStats,
    courses,
    careerRoles,
    sourceNote: "基于 2021 级电子信息工程专业（物联网方向）培养方案整理，卡片组已排除政治、就业指导、职业规划、劳动实践、创新创业类课程，以及大学物理、大学物理实验、大学体育和军事理论类课程。",
  },
  "electronic-info": {
    stats: electronicInfoStats,
    courses: electronicInfoCourses,
    careerRoles: electronicInfoCareerRoles,
    sourceNote: "基于 25 版电子信息工程专业培养方案整理，卡片组已排除政治、就业指导、职业规划、劳动实践、创新创业类课程，以及大学物理、大学物理实验、大学体育和军事理论类课程。",
  },
  "mobile-internet": {
    stats: mobileInternetStats,
    courses: mobileInternetCourses,
    careerRoles: mobileInternetCareerRoles,
    sourceNote: "基于 25 版电子信息工程专业（移动互联网方向）培养方案整理，卡片组已排除政治、就业指导、职业规划、劳动实践、创新创业类课程，以及大学物理、大学物理实验、大学体育和军事理论类课程。",
  },
  "communication-engineering": {
    stats: communicationEngineeringStats,
    courses: communicationEngineeringCourses,
    careerRoles: communicationEngineeringCareerRoles,
    sourceNote: "基于 25 版电子信息工程专业（通信工程方向）培养方案整理，卡片组已排除政治、就业指导、职业规划、劳动实践、创新创业类课程，以及大学物理、大学物理实验、大学体育和军事理论类课程。",
  },
};

export const semesterLabels = [
  "第一学期",
  "第二学期",
  "第三学期",
  "第四学期",
  "第五学期",
  "第六学期",
  "第七学期",
  "第八学期",
];
